version: '3.8'

services:
  postgres:
    container_name: postgres
    restart: always
    build:
      context: migration
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    restart: always
    build:
     context: backend
     dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  nginx:
    container_name: nginx
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/cond.d
      - ./var/www/static:/var/www/static
    ports:
      - "8080:80"
      - "443:443"
    links:
      - postgres
      - backend
    depends_on:
      - backend

volumes:
  data:

