version: '3.8'

services:
  postgres:
    container_name: postgres
    restart: always
    build:
      context: migration
      dockerfile: Dockerfile
    volumes:
      - postgres-data:/var/lib/data
    env_file:
      - .env
    ports:
      - "5433:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 81
    ports:
      - "5051:81"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  backend:
    container_name: backend
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  backend1:
    container_name: backend1
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8001:8001"

  backend2:
    container_name: backend2
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8002:8002"

  nginx:
    container_name: nginx
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/var/www/static:/var/www/static
      - ../img:/var/www/static/img
      - ../img:/etc/nginx/img
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - backend
      - pgadmin

volumes:
  postgres-data:
  pgadmin-data:
